backend:
  name: git-gateway
  repo: Belvedersky/marta-bra
  accept_roles:
    - admin
    - editor

site_url: https://martabra.ru
display_url: https://martabra.ru
media_folder: static/image
locale: 'ru'
show_preview_links: false

collections:

  - name: 'Cтраницы'
    label: 'Страницы'
    description: "Страницы на сайте"
    files:
      - label: 'Контакты'
        name: 'contacts'
        file: 'content/pages/сontacts.json'
        fields:
          - { label: 'Название', name: 'title', widget: 'string' }
          - { label: "Фото", name: "image", widget: "image" }
          - { label: 'Текст', name: 'body', widget: 'markdown' }

      - label: 'Сертификат'
        name: 'certificate'
        file: 'content/pages/certificate.json'
        fields:
          - { label: 'Название', name: 'title', widget: 'string' }
          - { label: "Фото", name: "image", widget: "image" }
          - { label: 'Текст', name: 'body', widget: 'markdown' }

      - label: 'Cотрудничество'
        name: 'cooperation'
        file: 'content/pages/cooperation.json'
        fields:
          - { label: 'Название', name: 'title', widget: 'string' }
          - { label: "Фото", name: "image", widget: "image" }
          - { label: 'Текст', name: 'body', widget: 'markdown' }
  - label: "Каталог"
    name: "каталог"
    description: "Каталог магазина Martabra"
    folder: 'content/catalog'
    create: true
    editor:
      preview: false
    fields:
        - { label: "Название", name: "title", widget: "string"}
        - {label: "Описание", name: "description", widget: "text"}
        - { label: "Стоимость", name: "price", widget: "number", valueType: "int", default: 0}
        - {label: "Скидка", name: "sale", widget: "boolean", default: false, required: false}
        - { label: "Фото", name: "image", widget: "image" }
        - {label: "Фоточки", name: "gallery", widget: "list", required: false,  field: {label: Image, name: image, widget: image}}

  - label: 'Блог'
    name: 'блог'
    description: "Блог Martabra"
    folder: 'content/blog'
    create: true
    fields:
       - { label: "Название", name: "title", widget: "string"}
       - { label: "Фото", name: "image", widget: "image" }
       - {label: "Описание", name: "description", widget: "text"}
       - {label: "Галерея", name: "photo", widget: "list",  field: {label: Image, name: image, widget: image}}
