backend:
  name: git-gateway
  branch: master

site_url: https://marta-bra.netlify.com
media_folder: public/lingerie
publish_mode: editorial_workflow

collections:
  - name: "Catalog"
    label: "Каталог"
    description: "Shop marta_bra"
    files:
      - label: "tour"
        name: "Tour"
        file: "public/data/tours.json"
        create: true
        fields:
          - label: "Tour List"
            name: "tourList"
            widget: "list"
            fields:
              - {label: "Tour Date", name: "date", widget: "datetime"}
              - {label: "Total Places", name: "totalPlaces", widget: "number"}
              - {label: "Filled Places", name: "filledPlaces", widget: "number"}
