backend:
  name: git-gateway
  branch: master

site_url: https://marta-bra.netlify.com
media_folder: public/lingerie
publish_mode: editorial_workflow

collections:
  - name: "Catalog"
    label: "Каталог"
    description: "Shop marta_bra"
    create: true
    extension: json
    files:
      - label: "Catalog"
        name: "Catalog"
        file: "public/data/tours.json"
        fields:
          - label: "Catalog"
            name: "tourList"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Body", name: "body", widget: "string"}

    