backend:
  name: git-gateway
  branch: master

site_url: https://marta-bra.netlify.com
media_folder: public/lingerie

collections:
  - name: "Catalog"
    label: "Каталог"
    description: "Shop marta_bra"
    create: true
    extension: json
    files:
      - label: "Catalog"
        name: "Catalog"
        file: "public/data/data.json"
        fields:
          - label: "Catalog"
            name: "CatalogList"
            widget: "list"
            fields:
              - { label: "link", name: "layout", widget: "hidden", default: "complect"}
              - { label: "Название", name: "title", widget: "string"}
              - {label: "Описание", name: "description", widget: "text"}
              - { label: "Стоимость", name: "price", widget: "string" }
              - { label: "Фото", name: "image", widget: "image" }

    