backend:
  name: git-gateway
  repo: Belvedersky/marta-bra
  accept_roles:
    - admin
    - editor

site_url: https://martabra.ru
display_url: https://martabra.ru
logo_url: /img/favicon.png
media_folder: public/lingerie
locale: 'ru'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

show_preview_links: false

collections:
  - name: 'Pages'
    description: "Cтраницы на сайте"
    editor:
      preview: false
    label: 'Cтраницы'
    files:
      - label: 'Контакты'
        name: 'contacts'
        file: 'public/data/pages/contacts.json'
        fields:
          - { label: 'Название', name: 'title', widget: 'string' }
          - { label: 'Текст', name: 'body', widget: 'markdown' }

      - label: 'Сертификат'
        name: 'certificate'
        file: 'public/data/pages/certificate.json'
        fields:
          - { label: 'Название', name: 'title', widget: 'string' }
          - { label: 'Текст', name: 'body', widget: 'markdown' }

      - label: 'Cотрудничество'
        name: 'cooperation'
        file: 'public/data/pages/cooperation.json'
        fields:
          - { label: 'Название', name: 'title', widget: 'string' }
          - { label: 'Текст', name: 'body', widget: 'markdown' }
          
        

  - name: "Catalog"
    label: "Каталог"
    description: "Каталог магазина Martabra"
    create: false
    extension: json
    editor:
      preview: false
    files:
      - label: "Каталог"
        name: "Catalog"
        file: "public/data/catalog/catalog.json"
        slug: '{{slug}}'
        fields:
          - label: "Каталог"
            name: "CatalogList"
            widget: "list"
            fields:
              - { label: "Название", name: "title", widget: "string"}
              - {label: "Описание", name: "description", widget: "text"}
              - { label: "Стоимость", name: "price", widget: "number", valueType: "int", default: 0}
              - {label: "Скидка", name: "sale", widget: "boolean", default: false, required: false}
              - { label: "Фото", name: "image", widget: "image" }
              - {label: "Фоточки", name: "gallery", widget: "list", required: false,  field: {label: Image, name: image, widget: image}}

      - label: "Блог"
        name: "Catalog"
        file: "public/data/blog.json"
        slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
        fields:
          - label: "Blog"
            name: "blog"
            widget: "list"
            fields:
              - { label: "Название", name: "title", widget: "string"}
              - {label: "Описание", name: "description", widget: "text"}
              - {label: "Галерея", name: "photo", widget: "list",  field: {label: Image, name: image, widget: image}}
    